# Generated by Django 2.1.1 on 2018-10-14 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=32)),
                ('employee_surname', models.CharField(max_length=32)),
                ('employee_hours', models.IntegerField()),
                ('employee_hourly_pay', models.FloatField()),
                ('employee_wage_gross', models.FloatField()),
                ('employee_wage_net', models.FloatField()),
            ],
        ),
    ]
