# Generated by Django 2.1.1 on 2018-10-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=32)),
                ('employee_surname', models.CharField(max_length=32)),
                ('employee_hours', models.IntegerField(blank=True, null=True)),
                ('employee_hourly_pay', models.IntegerField(blank=True, null=True)),
                ('employee_wage_gross', models.IntegerField(blank=True, null=True)),
                ('employee_wage_net', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_hourly_pay',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_wage_gross',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_wage_net',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
