# Generated by Django 2.1.1 on 2018-11-03 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20181029_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='hourly_pay',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hours',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='wage_gross',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='wage_net',
            field=models.IntegerField(blank=True),
        ),
    ]
