# Generated by Django 2.1.1 on 2018-11-03 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20181103_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='hourly_pay',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hours',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='wage_gross',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='wage_net',
            field=models.PositiveIntegerField(),
        ),
    ]
