# Generated by Django 2.1.1 on 2018-11-14 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20181106_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletedemployee',
            name='hourly_pay',
            field=models.IntegerField(verbose_name='Stawka godzinowa(PLN)'),
        ),
        migrations.AlterField(
            model_name='deletedemployee',
            name='hours',
            field=models.IntegerField(verbose_name='Ilość godzin'),
        ),
        migrations.AlterField(
            model_name='deletedemployee',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='deletedemployee',
            name='surname',
            field=models.CharField(max_length=32, verbose_name='Nazwisko'),
        ),
        migrations.AlterField(
            model_name='deletedemployee',
            name='wage_gross',
            field=models.IntegerField(verbose_name='Suma brutto(PLN)'),
        ),
        migrations.AlterField(
            model_name='deletedemployee',
            name='wage_net',
            field=models.IntegerField(verbose_name='Suma netto(PLN)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hourly_pay',
            field=models.PositiveIntegerField(verbose_name='Stawka godzinowa(PLN)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hours',
            field=models.PositiveIntegerField(verbose_name='Ilość godzin'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='surname',
            field=models.CharField(max_length=32, verbose_name='Nazwisko'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='wage_gross',
            field=models.PositiveIntegerField(verbose_name='Suma brutto(PLN)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='wage_net',
            field=models.PositiveIntegerField(verbose_name='Suma Netto(PLN)'),
        ),
    ]
